services:
  - type: web
    name: smart-leads-backend
    env: docker
    plan: free
    region: oregon
    repo: https://github.com/tiwaritanay01/smart_leads_dashboard
    branch: main
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: MONGO_URI
      - key: JWT_SECRET
      - key: JWT_EXPIRES_IN
      - key: NODE_ENV
      - key: PORT
      - key: FRONTEND_ORIGIN
